### ISSUE TITLE
[trac import 1/17/15] Content breaks on smaller screens on default template

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1237]
Open:  http://demo.eden.sahanafoundation.org/eden/
Breakpoint tested: 650px and below
Expected result: Content scales with fluidity and resizes to current viewport size. Content will fit into the view window with padding at the side for mobile users to view easily. No scroll bars or overflow occurs.
Actual result: Content does not resize, and overflows off the screen, becoming unviewable. Screenshot is attached to show the problem. User has to scroll left and right to see the content, reducing user friendliness and usability.

![wireframe](https://cloud.githubusercontent.com/assets/444311/13557353/c1de5be0-e3bc-11e5-9412-abf6b09b23ea.png)
![responsive1](https://cloud.githubusercontent.com/assets/444311/13557352/c1db5468-e3bc-11e5-8874-b6773fc8c90a.jpg)

**Comment by nursix** [comment]
This problem has been solved in the new default homepage design.
