### ISSUE TITLE
[trac import 7/4/14 by dominic] .iframe open links not always working

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1246]
When viewing a datatable in an iframe, then the Open links should open in .iframe mode too.
This works for this URL:
 http://127.0.0.1:8000/eden/org/organisation.iframe/1/office
But not this one:
 http://127.0.0.1:8000/eden/org/organisation/1/office.iframe

**Comment by nursix** [comment]
Fixed in trunk.
