### ISSUE TITLE
[trac import 4/21/14 by anurag029] Homepage gets broken on opening it on Chromebook

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1248]
I was setting up my development environment on a ARM based Chromebook and the homepage is broken even the demo site has the same condition.
![44 pm](https://cloud.githubusercontent.com/assets/444311/13557529/f61dd784-e3bf-11e5-8c8c-1671b17c77cc.png)

**Comment by nursix** [comment]
Fixed in new default homepage design.
