### ISSUE TITLE
[trac import 3/17/14 by somayjain] DRMP : Adding subscriptions with names having non ascii characters.

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1249]
1. Change the template to DRMP.
2. Delete the databases and restart web2py and prepoluate the database.
3. Login with username :  admin@example.com and password : testing
4. Go to  http://127.0.0.1:8000/eden/default/index/subscriptions and check Lautém in Locations.
5. Click on "Update Settings"
6. Refresh the page.

You will get a ticket giving a exceptions.UnicodeEncodeError?.

**Comment by nursix** [comment]
Fixed in trunk.
