### ISSUE TITLE
[trac import 2/19/14 by iamas] For Hide MultiSelect Widgets until they are properly rendered with the multiselect JS

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1252]
While running the smoke tests in an environment where proxy is set, smoke tests do not consider the no proxy environment variable. Thus, if you have proxy set, you can not run smoke tests on your localhost. Most probably, the problem lies with twill and how it is not able to fetch a page on the localhost if proxy is set.

**Comment by nursix** [comment]
obsolete
