### ISSUE TITLE
[trac import 2/3/14 by flavour] Chosen widget doesn't work when unhiding a create form

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1254]
e.g. /eden/gis/hierarchy
works fine via:
/eden/gis/hierarchy/create
This widget is:
 https://github.com/flavour/eden/blob/master/static/scripts/chosen.jquery.js
I guess it needs re-initialising once the create form is unhidden

**Comment by huynhv** [comment]
Hi @devinbalkind, the link you post no longer works. Can you link to it again?

**Comment by devinbalkind** [comment]
@flavour

**Comment by nursix** [comment]
Doesn't exist anymore. Can probably be closed.
