### ISSUE TITLE
[trac import 1/6/14 by dominic] Default Theme wrongly overflowing to the right in RTL

### ISSUE THREAD

**Issue by devinbalkind** [sahana/eden#1256]
Default Theme, in right-to-left languages (e.g. Urdu):

- the top menu is not properly reversed (Modules are still left and Admin menu right - should be vice versa)
- the main contents is not reversed either (Controller menu is left - should be right)
- the main scrolls (correctly) to the left - but overflows (wrongly) to the right, hence leaving parts of the contents inaccessible

Suggested solution:
The flow and margin rules for the .fright, .fleft, .col1, .col2, .col3 and .aside classes need to be adapted when body is set to .rtl.

![urdu1](https://cloud.githubusercontent.com/assets/444311/13557630/adeae72e-e3c2-11e5-9eba-50357d8945f3.png)
![urdu2](https://cloud.githubusercontent.com/assets/444311/13557632/adeb2c5c-e3c2-11e5-8937-56caeee66ed1.png)
![urdu3](https://cloud.githubusercontent.com/assets/444311/13557631/adeb1104-e3c2-11e5-951b-04a2825ba798.png)

**Comment by nursix** [comment]
This problem can no longer be reproduced with the new default theme.
