### ISSUE TITLE
PyDAL Incompatibility problems with web2py > 2.14.5

### ISSUE THREAD

**Issue by ovnicraft** [sahana/eden#1280]
With a fresh installation, in Debian 7 i change to use postgresql as DB using [this](https://gist.github.com/ovnicraft/ab17044f307221b9dc6d0c7479622475l) to deploy from [our fork](https://github.com/desastre-ecuador/eden/commit/669f8b5105bd508ab019c1ffea0a1b6559567169) but i got the error:

object has no attribute INVERT = current.db._adapter.INVERT

i found this at https://github.com/sahana/eden/blob/master/modules/s3/s3data.py#L112
I am using psycopg2 driver and try both installations from debian repo an pip but nothing works.

**Comment by nursix** [comment]
Cristian -- please see the other thread. Use web2py 2.14.5 to solve this problem.

**Comment by nursix** [comment]
Copying from the other thread:

Please revert to web2py 2.14.5 to solve this problem. 

    cd /home/web2py 
    git reset --hard 81d0291 

The PyDAL component of web2py is currently undergoing a major restructuring, breaking backwards-compatibility and thereby loads of our code. Until this is fixed, and our code adapted accordingly please use 2.14.5.

Web2py still declares the new PyDAL as experimental - and since this is an incompatible change, we won't adapt Sahana just yet.

**Comment by ovnicraft** [comment]
@nursix ok i will try and comment

**Comment by ovnicraft** [comment]
@nursix i still get the error

`AttributeError: 'PostgrePsyco' object has no attribute 'INVERT'`

Here full traceback https://gist.github.com/ovnicraft/2b236bd612ccc2402ef2a578d034c51f

**Comment by nursix** [comment]
Yeah - correct. Sorry, I forgot that one.

    git submodule update

...in the web2py folder

**Comment by ovnicraft** [comment]
@nursix ok, i did it so when try to access to platform now i get this https://gist.github.com/ovnicraft/b43bf3e55576fb3dba003da6f263d8c3

`<class 'psycopg2.ProgrammingError'> la columna «worker_stats__tmp» es de tipo json pero la expresión es de tipo text LINE 1: UPDATE scheduler_worker SET worker_stats__tmp=worker_stats; `

**Comment by nursix** [comment]
Could you try to clean the database (=drop it, then create it new), and then try running it again?

**Comment by nursix** [comment]
Don't forget to delete everything in the databases/ subfolder after you dropped the database ;)

**Comment by ovnicraft** [comment]
i did it but now get `Cannot connect to postgres Database: localhost:5432/sahana`

I create it new and sahana user is the owner ?

how i can debug it from console ?

**Comment by ovnicraft** [comment]
i got this with `psql -l`

```
csalamea@prod-desastre-eden:/home/web2py$ psql -l 
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | es_EC.UTF-8 | es_EC.UTF-8 | 
 sahana    | sahana   | UTF8     | es_EC.UTF-8 | es_EC.UTF-8 | 
```

**Comment by nursix** [comment]
So, you dropped the "sahana" database, created it new, and after that it says "cannot connect to postgres database"? Are you sure you restarted Sahana after that?

If it could access it before, it should also be able to access it afterwards.

Console won't give you any other error, but you can do something like this:

    python web2py.py -S eden -M -R applications/eden/static/script/tools/noop.py

...from the web2py folder. If this crashes with the same error, then we need to try again with the database reset...

**Comment by ovnicraft** [comment]
Now its populating database, i hope this works and we can deploy eden ASAP.
