### ISSUE TITLE
Import error for portallocker

### ISSUE THREAD

**Issue by Onalu** [sahana/eden#1319]
Hi, 

I have come across a import error while I was running ``configure-eden-cherokee-postgis.sh``
Trace is like this:
> Traceback (most recent call last):
>   File "/home/web2py/gluon/restricted.py", line 220, in restricted
>     exec(ccode, environment)
>   File "applications/eden/models/000_1st_run.py", line 73, in <module>
>     from gluon import portalocker
> ImportError: cannot import name portalocker

I think it is related to a [recent change](https://github.com/web2py/web2py/commit/cc1ff0207993a8b1c2746575dd9ca961f52a5916#diff-0067ab6b6032f36efefb2d10cefdfdb6) in web2py. 

Regards.

**Comment by flavour** [comment]
As per mailing list thread, we currently only support the latest stable web2py:
https://groups.google.com/forum/#!searchin/sahana-eden/portalocker%7Csort:relevance/sahana-eden/3NmgZrCTdU0/Ak0SfqmWAwAJ
