### ISSUE TITLE
Errors in default config.py

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1371]
There are multiple issues in *default* template configuration file.

1. There is a following commented directive
    ```python
    #settings.ui.menu_logo = URL(c="static", f="img", args=["S3menulogo.png"])
    ```
    Uncommenting the line is not sufficient to activate the directive as the `URL()` method is not imported, therefore following line
    ```python
    from gluon.html import URL
    ```
    should be added to imports in the beginning of the file.

2. There is a missing double quote in `label` key in commented `settings.gis.poi_create_resources` directive value.
    Current:
    ```python
    #settings.gis.poi_create_resources = [{"c":"event", "f":"incident_report", "table": "gis_poi", label": T("Add Incident Report") ,"tooltip": T("Add Incident Report"), "layer":"Incident Reports", "location": "popup"}]
    ```
    Correct:
    ```python
    #settings.gis.poi_create_resources = [{"c":"event", "f":"incident_report", "table": "gis_poi", "label": T("Add Incident Report") ,"tooltip": T("Add Incident Report"), "layer":"Incident Reports", "location": "popup"}]
    #----------------------------------------------------------------------------------------------^
    ```

3. Uncommenting the `settings.inv.item_status` dictionary fail with following error
    ```
    Traceback (most recent call last):
      File "/srv/sahana/gluon/restricted.py", line 227, in restricted
        exec ccode in environment
      File "applications/eden/models/000_config.py", line 228, in <module>
        settings.import_template()
      File "applications/eden/modules/s3cfg.py", line 266, in import_template
        template.config(self)
      File "applications/eden/modules/templates/default/config.py", line 812, in config
        0: current.messages["NONE"],
    AttributeError: 'thread._local' object has no attribute 'messages'
    ```
    The culprit is the key `0: current.messages["NONE"]`. The other templates seem to have the reference to `current.messages` always in a function and never in global scope.

**Comment by nursix** [comment]
For point 1:

The default/config.py file shall not have any settings uncommented - these are rather just examples to illustrate the usage in other templates or models/000_config.py (i.e. they are copy+paste templates, or documentation, if you will).

In the default template, they shall (it's in the name) always *default*. And consequently, there shall be no imports of anything either - those would just cause unnecessary processing.

So, these issues are not /bugs/ but incorrect examples/comments/documentation.

As for point 2: this seems like a typo - easy enough to correct this example
As for point 3: indeed you can not use current.messages in the config() function itself (because it is only defined afterwards), it must be wrapped into a callback - so this observation is correct. The example should be corrected

**Comment by nursix** [comment]
Btw - instead of posting the corrected code into the issue report (point 2), you could as well have sent a pull request.

**Comment by huynhv** [comment]
Seems like Point 2 is already fixed.

As for Point 3:
When I uncomment these lines there was a server error but I did not know where to locate the error log. So when I played around after this and changed from current.messages["None"] to T("None"), the error went away but I don't know what has changed.

Can you clarify this? 
Thanks.

**Comment by nursix** [comment]
The explanation can be found above: ```current.messages``` is defined only after 000_config.py is executed, so you can not reference it there.

```T()``` in turn is defined before 000_config.py is executed, so you can use it there.

However, ```current.messages["NONE"]``` usually translates into ```"-"```, not ```"None"```, so ```T("None")``` isn't equivalent. 

But replacing ```current.messages["NONE"]``` by simply ```"-"``` should be perfectly adequate for the example.

**Comment by AlexanderLaughlin** [comment]
Is this still an open issue?

**Comment by flavour** [comment]
Should be easy enough to check...

**Comment by nursix** [comment]
> But replacing current.messages["NONE"] by simply "-" should be perfectly adequate for the example.

This has not been done yet, and it is all that needs doing to resolve this issue.
