### ISSUE TITLE
Setting presence on login results in HTTP 400 - Bad Request

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1378]
Setting `settings.auth.set_presence_on_login = True` and trying to log in result in following stack trace printed in Web2py console output.
```
ERROR:Rocket.Errors.Thread-9:Traceback (most recent call last):
  File "/srv/sahana/gluon/rocket.py", line 1337, in run
    self.run_app(conn)
  File "/srv/sahana/gluon/rocket.py", line 1838, in run_app
    output = self.app(environ, self.start_response)
  File "/srv/sahana/gluon/main.py", line 653, in app_with_logging
    ret[0] = wsgiapp(environ, responder2)
  File "/srv/sahana/gluon/main.py", line 564, in wsgibase
    return wsgibase(new_environ, responder)
  File "/srv/sahana/gluon/main.py", line 534, in wsgibase
    if request.body:
  File "/srv/sahana/gluon/globals.py", line 281, in body
    raise HTTP(400, "Bad Request - HTTP body is incomplete")
HTTP: 400 BAD REQUEST
```

This is likely a *Web2py* framework error, but it's strange that the error is triggered just by using geolocation API. The reason given in stack trace would suggest that the `Content-Length` header sent by client and the actual content length differ, but they do not. I was able to get the same error using both Firefox and Chrome browsers (both with HTTPS enabled as plain HTTP does not allow geolocation API to be used).

**Comment by nursix** [comment]
I don't think it's a web2py error - it may well be an error in the client-side form processing.

**Comment by trendspotter** [comment]
Clarification: The stack trace above is reported when SE runs directly via web2py server. When running via nginx+uwsgi, following stack trace is shown in SE ticket instead.
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/default.py", line 1547, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/default.py", line 298, in index
    login_form = auth.login(inline=True)
  File "applications/eden/modules/s3/s3aaa.py", line 759, in login
    self.login_user(user)
  File "applications/eden/modules/s3/s3aaa.py", line 994, in login_user
    locations = gis.get_features_in_radius(userlat, userlon, accuracy)
  File "applications/eden/modules/s3/s3gis.py", line 2088, in get_features_in_radius
    connection = psycopg2.connect("dbname=%s user=%s password=%s host=%s port=%s" % (dbname, username, password, host, port))
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: could not translate host name "None" to address: Name or service not known
```

**Comment by nursix** [comment]
This can probably be fixed by changing this:
https://github.com/sahana/eden/blob/master/modules/s3/s3gis.py#L2082

into:

    host = settings.database.host or "localhost"

If you have a test environment ready, could you check if this would fix it, and send a PR if so?

**Comment by nursix** [comment]
To explain it: settings.database.host is usually None to indicate that it should default, but get_features_in_radius doesn't apply any default. This would add it.

Alternatively, we could have a S3Config.get_database_host() that returns the default "localhost" for None, and then call that in get_features_in_radius (in fact, that would be the "correct" way - the settings dict shouldn't be accessed directly to prevent regression).

**Comment by trendspotter** [comment]
```
host = settings.database.host or "localhost"
```
Changes the traceback to 
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/default.py", line 1547, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/default.py", line 298, in index
    login_form = auth.login(inline=True)
  File "applications/eden/modules/s3/s3aaa.py", line 759, in login
    self.login_user(user)
  File "applications/eden/modules/s3/s3aaa.py", line 994, in login_user
    locations = gis.get_features_in_radius(userlat, userlon, accuracy)
  File "applications/eden/modules/s3/s3gis.py", line 2088, in get_features_in_radius
    connection = psycopg2.connect("dbname=%s user=%s password=%s host=%s port=%s" % (dbname, username, password, host, port))
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL:  password authentication failed for user "None"
```

So it seems that none of the database information are getting populated here.

**Comment by trendspotter** [comment]
Aaa, yeah.. because I don't have any `settings.database.username` and I'm relying on the *S3Config* to give me the default string. So your suggestion about `S3Config.get_database_*` applies also here.

**Comment by nursix** [comment]
Same problem there - even settings.database.user is None to indicate the default "sahana".

The correct way to solve it is to not access the settings dict directly, but have a getter-function in S3Config that applies the defaults (you can see the default in the modules/templates/000_config.py template).

A quick workaround would be to "or" the defaults here in the settings-lookups. But this wouldn't be robust for future changes of the defaults then, so I'd recommend the former.

However, your test confirms at least that the missing default is the problem.

**Comment by nursix** [comment]
:D right

**Comment by nursix** [comment]
I think, instead of having individual getters, we should have something similar to:
https://github.com/sahana/eden/blob/master/modules/s3cfg.py#L979

...which returns a dict with the database settings instead of a string.

This could then be used in get_database_string (i.e. DRY).

What do you think? Do you want to do this, or shall I?

**Comment by nursix** [comment]
E.g. S3Config.get_database_parameters() => takes the settings.database.*, applies all defaults (...which depend on the DB type), and then returns a dict with the parameters.

S3Config.get_database_string() would call get_database_parameters() and then construct the string from that dict rather than applying the defaults itself.

S3GIS.get_features_in_radius would also call settings.get_database_parameters(), but construct a different string from it.

**Comment by trendspotter** [comment]
> What do you think? Do you want to do this, or shall I?

Go for it. You know the codebase incomparably better than me. :) There's also similar approach as the GIS uses (this time with defaults) here: https://github.com/sahana/eden/blob/master/controllers/default.py#L1119 and few lines below that for PgSQL

**Comment by nursix** [comment]
Like this, maybe:
https://github.com/nursix/eden/commit/385b3de74d2da6627386c25fae0485039d3959e7

Now I don't currently have an active PostGIS installation locally - so I can only verify that it prevents the crash you described above, but not whether the setting of presence on login actually works. Could you maybe check that and confirm?

**Comment by trendspotter** [comment]
Following traceback during DB population. I guess the same thing as in [44cc117](https://github.com/nursix/eden/commit/44cc11731c0d9cee36a08b0bc7baf4d09200d669) has to be fixed
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "applications/eden/models/00_db.py", line 53, in <module>
    if settings.get_base_session_db():
  File "applications/eden/modules/s3cfg.py", line 909, in get_base_session_db
    (db_string, pool_size) = self.get_database_string()
ValueError: too many values to unpack
```

**Comment by nursix** [comment]
Okay, fixing it again...hang on...

**Comment by nursix** [comment]
This makes more sense then:
https://github.com/nursix/eden/commit/2d9254f416bd9f1cd9c6c84e0b090d3852cdd322

**Comment by nursix** [comment]
@trendspotter wait for the unit tests to complete - they actually caught the issue.

**Comment by nursix** [comment]
Okay, passing now:
https://travis-ci.org/nursix/eden/builds/279191755

NB I updated the original commit rather than adding on top of it, so you may need to rewind a little bit.

**Comment by nursix** [comment]
Btw - maybe we should have live conversation on IRC freenode/#sahana-eden. Otherwise I will get whipped for spamming people here :$

**Comment by trendspotter** [comment]
DB population works, login works and `auth_user_clientlocation` has correct data, so these are definitely OK.  `gis.get_features_in_radius()` doesn't seem to return anything even though I have a feature right on my coords, but that can already be a problem with my data (and if not, it didn't work up until now anyway).

So.. nice job here, I think it can go to the master.

**Comment by nursix** [comment]
Cool, so let's wait for the merge, then close the issue. Thanks for checking.
