### ISSUE TITLE
Consider running static code analysis (lint)

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1379]
There seems to be many undefined variables and function calls throughout the whole *Sahana Eden* code. Consider running static analysis, using tools such as *pylint*.

The analysis can be performed as follows
```
pip install ipdb pylint pylint-web2py2

cd /home/web2py/applications
/usr/local/bin/pylint -E --load-plugins=pylint_web2py2 eden
```
See attached [pylint.txt](https://github.com/sahana/eden/files/1297293/pylint.txt) for possible result of the commands above. The `-E` parameter causes pylint to report only severe errors. This could help to prevent errors such as #1372, #1375, #1376 and #1377.

Note: Heavily outdated libs like PyQt4.QtWebKit, geopy.parsers were not installed on my instance and are throwing 'import-error' in the report.

**Comment by nursix** [comment]
This is not a bug, but a recommendation. For such, please use the mailing list, not the issue tracker.
Thanks!

**Comment by nursix** [comment]
NB It only /seems/ that there are many undefined variables and function calls throughout the code - but you have been analyzing a lot of unused/outdated code (which is either kept as historic reference, or as c/p templates).

That's the downside of running pylint against the entire code base ;) you will find quite a lot of ghosts.

However, running pylint (or jshint, for the JS parts) is indeed part of my routine, so I would second your recommendation - it is very helpful indeed *if* you know what you're looking at.

It is though /not/ so very helpful to publish the output here with the suggestion that there are tons of bugs - either you verify every single one of them (and check that they are in active code), or you put in a disclaimer (...although then it doesn't belong on the issue tracker, but I said that already).

Nevertheless - good digging.
