### ISSUE TITLE
GIS: Layer Properties show blank popup

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1391]
Clicking on *Layer Properties* button above the GIS map tree displays a popup where apparently the configuration for the selected layer should appear. The popup does show up, but the content of the *Layer Properties* tab is empty. There is no ticket created, only following JS stack trace in console.
```
Uncaught TypeError: S3.autocomplete is not a function
    at success (s3.gis.js:6143)
    at Ext.data.Connection.handleResponse (ext-all-debug.js:4661)
    at Object.complete (ext-jquery-adapter-debug.js:1946)
    at fire (jquery-1.11.3.js:3148)
    at Object.fireWith (jquery-1.11.3.js:3260)
    at done (jquery-1.11.3.js:9329)
    at XMLHttpRequest.callback (jquery-1.11.3.js:9718)
```

The `S3.autocomplete` indeed is not a function itself. It's an object containing functions, however I have no clue if this alone is the cause and how to fix it.

Moreover, the *Filter* tab in the popup doesn't seem to be working as intended either.

**Comment by nursix** [comment]
Try replacing ```S3.autocomplete``` with ```S3.autocomplete.normal``` in s3.gis.js

**Comment by trendspotter** [comment]
JS trace is gone but the *Layer Properties* tab is still empty.

**Comment by trendspotter** [comment]
FWIW, the tab tries to get content from ULR like `http://<host>/eden/gis/layer_feature.plain?layer_feature.layer_id=15&update=1&_dc=1506434920847` but get only this as response body (including blank lines):
```







<div id='plain'>

</div>
```

It has been brought to my attention that the same issue exists also on <http://rmsdemo.aidiq.com/eden/gis/index> which I personally can't confirm since I don't have access there (yet).

**Comment by nursix** [comment]
https://github.com/nursix/eden/commit/270108e9f0c4e4f1b1ef1346257b2fe6659bcb29

should solve that.

**Comment by trendspotter** [comment]
And it does. One character and so much damage :)  
Thanks

**Comment by trendspotter** [comment]
Btw. what about the *Filter* tab? Currently it seems to render whole SE GIS window again, as it sends AJAX request to `https://<host>/eden/gis/index`.

**Comment by nursix** [comment]
Pass...I'm not sure this has ever been migrated to the current framework, and this may also be beyond this issue.

Make sure to send a PR with the s3.gis.js fix ;)

**Comment by flavour** [comment]
Yes, as it says here:
https://github.com/sahana/eden/blob/master/static/scripts/S3/s3.gis.js#L6056

@ToDo: Migrate to S3Filter!

It used the old S3Search framework when originally written and hasn't been updated to use S3Filter
