### ISSUE TITLE
Survey summary throws either error 500 or Unsupported method

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1394]
Steps to reproduce:
1. Use *Survey* module to create a *Disaster Assessment* (or reuse an existing one)
2. Import or enter at least one completed assessment form
3. Open the assessment and go to the *Summary* tab

Following leads to `Unsupported method`:

4. Select a single question with at least one reply
5. Click on *Display Selected Questions*
6. Click on *Open*

Following leads to error 500:

4. Click on *Select all*
5. Click on *Display Selected Questions*
6. Click on *Open*

In RMS template, the steps above lead to following error instead:
```
{"status": "failed", "message": "METHOD NOT ALLOWED", "statuscode": "405"}
```

Traceback for the error 500:
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/survey.py", line 1168, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/survey.py", line 299, in series
    output = s3_rest_controller(rheader=s3db.survey_series_rheader)
  File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 688, in __call__
    output = handler(self, **attr)
  File "applications/eden/modules/s3db/survey.py", line 1671, in seriesSummary
    form = buildSeriesSummary(series_id, posn_offset)
  File "applications/eden/modules/s3db/survey.py", line 2355, in buildSeriesSummary
    questions = survey_getAllQuestionsForSeries(series_id)
  File "applications/eden/modules/s3db/survey.py", line 1114, in survey_getAllQuestionsForSeries
    template_id = row.template_id
AttributeError: 'NoneType' object has no attribute 'template_id'
```

The behaviour can be observed also in both <http://demo.eden.sahanafoundation.org/eden/survey/series/> and <http://rmsdemo.aidiq.com/eden/survey/series>

Additionally, the table in step 6. has a header with no labels in *default* template.

**Comment by trendspotter** [comment]
Seems that the URL in table in step 6. is created with wrong ID.

Eg with default data in RMS template, it leads to `http://<host>/eden/survey/series/Ms.%20Mario%20Moniz/summary`. In default template it leads to `http://<host>/eden/survey/series//summary` (the ID is missing entirely there).

**Comment by flavour** [comment]
Note that the Survey module is being deprecated & replaced by the DC module (Data Collection)
This can be seen using the SCPHIMS template where itis called 'Assessments'
DC uses the dynamic tables back-end & so will be fully integrated into the framework, usable on Mobiles, etc.
However there are a few features that are unlikely to be ported from the old Survey module, so it would be good to get this fixed still.

**Comment by flavour** [comment]
ok, there shouldn't be any Open button at all...this is being automated which the page isn't expecting...it just wants a formatted table!

**Comment by flavour** [comment]
Fixed: https://github.com/sahana/eden/commit/978f0c25c8d85bef6c4a7d535dd7481784a773b7
Unfortunately mixed with my other work...but no time to unpick
