### ISSUE TITLE
org_SiteRepresent strips records when multiple facility types per site are used

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1400]
When a facility has multiple types, the `S3Represents` strips rows from SQL results, causing eg. *Manage Your Facilities* on the homepage to show names as the string set in `messages["UNKNOWN_OPT"]`.

Steps to reproduce:

1. Create *Facility Type* with name `Type 1`
2. Create *Facility Type* with name `Type 2`
3. Create *Facility* with name `Facility 1`, assign both `Type 1` and `Type 2`.
4. Create *Facility* with name `Facility 2` (assignment doesn't matter)
5. Observe *Manage Your Facilities* dropdown on homepage
![image](https://user-images.githubusercontent.com/15286128/31056438-c958bc1a-a6d1-11e7-82b1-fc3d12317be5.png)

Cause:

[Line 768 in s3fields.py](https://github.com/sahana/eden/blob/master/modules/s3/s3fields.py#L758) generates following query:
```
SELECT org_site.site_id, org_site.instance_type, org_site.name, org_facility_type.name
  FROM org_site LEFT JOIN org_site_facility_type ON (org_site_facility_type.site_id = org_site.site_id) LEFT JOIN org_facility_type ON (org_site_facility_type.facility_type_id = org_facility_type.id)
  WHERE (org_site.site_id IN (1,2)) ORDER BY org_site.site_id, org_facility_type.id
  LIMIT 2 OFFSET 0;
```
Since the `org_site_facility_type` is `LEFT JOIN`ed, it generates multiple rows in the result set (one for each facility type) and subsequent `LIMIT` (which is set to `len(lookup.keys())`) strips the exceeding result rows.

**Comment by nursix** [comment]
The actual function at fault is this:
https://github.com/sahana/eden/blob/master/modules/s3db/org.py#L5504

**Comment by nursix** [comment]
Correct is, however, that custom_lookup_rows must return exactly one row per site_id - it is not allowed to have multiple result rows (=multiple representations) per site_id.

And yet, that one row should contain all facility type IDs for that site_id, not just the first one.

**Comment by nursix** [comment]
Best option is to
- not left-join the facility type at all, but
- run a secondary query for the type links, then collect the facility_type_ids per site_id
- use a the facility_type_id representation function to bulk-represent the facility_type_ids
- add the list of facility_type_ids to each site row, so that represent_row can pick it up
- represent_row  then renders a comma-separated type name list in the brackets

This would also be more efficient than the double-join.

This seems like an easy fix, do you want to go for it?

**Comment by trendspotter** [comment]
My initial idea was to add a `GROUP_CONCAT()` to the SQL query, but I have no idea if that's even within realm of possibilities. The database object model (and by extension whole Web2py's pyDAL) is one of the few things where I'm still completely lost, as it doesn't resemble anything I've worked with so far (which was mostly C# and PHP... plus, I'm primarily a sysadmin, not a programmer :) ), so if you don't mind, until I have at least a notion about this whole abstraction thing, I'd rather not push any PR where DB relations come into play yet.

**Comment by nursix** [comment]
Okay, no problem. I can fix it - and optimize it along the way. Give me an hour.

**Comment by nursix** [comment]
You could try this:
https://github.com/nursix/eden/commit/282f45b186298c891e0ac9658111b4e9064895f8

Let me know if it works.

**Comment by trendspotter** [comment]
Works like a charm. Thanks.

**Comment by nursix** [comment]
And to answer your doubt about GROUP_CONCAT - you're right, this is rather remote. 

GROUP_CONCAT is pretty much a MySQL invention. There are similar functions in a few other SQL implementations - but no defined standard, and so we would need a different solution for each DBMS that supports something of that kind plus a Python-side alternative for those which don't.

That would certainly be /possible/, but not very smart from a code maintenance perspective - and given that the Python-side alternative is needed anyway, we can settle for just that.
