### ISSUE TITLE
Assigning an asset causes error

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1405]
How to reproduce:
1. Create an organsation
2. Create a facility belonging to the organisation above
3. Create an asset (eg. air compressor) belonging to the facility above
4. Open the asset and click on one of *Assign to Person*, *Assign to Facility/Site* or *Assign to Organization*

An error with following traceback will occur:
```
Traceback (most recent call last):
  File "/srv/sahana/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/srv/sahana/applications/eden/controllers/asset.py", line 217, in <module>
  File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
    self._caller = lambda f: f()
  File "/srv/sahana/applications/eden/controllers/asset.py", line 47, in asset
    return s3db.asset_controller()
  File "applications/eden/modules/s3db/asset.py", line 1291, in asset_controller
    rheader = asset_rheader,
  File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
    output = r(**attr)
  File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
    output = self.resource.crud(self, **attr)
  File "applications/eden/modules/s3/s3rest.py", line 1774, in __call__
    output = self.apply_method(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 101, in apply_method
    output = self.create(r, **attr)
  File "applications/eden/modules/s3/s3crud.py", line 392, in create
    format=representation,
  File "applications/eden/modules/s3/s3forms.py", line 516, in __call__
    buttons = buttons)
  File "/srv/sahana/gluon/sqlhtml.py", line 1295, in __init__
    inp = self.widgets.options.widget(field, default)
  File "/srv/sahana/gluon/sqlhtml.py", line 313, in widget
    options = requires[0].options()
  File "/srv/sahana/gluon/validators.py", line 2649, in _options
    options = self.other.options(*args, **kwargs)
  File "applications/eden/modules/s3/s3validators.py", line 1093, in options
    self.build_set()
  File "applications/eden/modules/s3/s3validators.py", line 814, in build_set
    show_link=False)
  File "applications/eden/modules/s3db/org.py", line 5489, in bulk
    labels = self._lookup(values, rows=rows)
  File "applications/eden/modules/s3/s3fields.py", line 762, in _lookup
    rows = self.lookup_rows(key, lookup.keys(), fields=fields)
  File "applications/eden/modules/s3db/org.py", line 5545, in custom_lookup_rows
    ltable = s3db.org_site_facility_type
  File "applications/eden/modules/s3/s3model.py", line 156, in __getattr__
    AttributeError("undefined table: %s" % name))
  File "applications/eden/modules/s3/s3model.py", line 226, in table
    model(prefix)
  File "applications/eden/modules/s3/s3model.py", line 100, in __init__
    env = self.model()
  File "applications/eden/modules/s3db/org.py", line 4152, in model
    options = self.req_priority_opts,
  File "applications/eden/modules/s3/s3model.py", line 156, in __getattr__
    AttributeError("undefined table: %s" % name))
  File "applications/eden/modules/s3/s3model.py", line 226, in table
    model(prefix)
  File "applications/eden/modules/s3/s3model.py", line 100, in __init__
    env = self.model()
  File "applications/eden/modules/s3db/req.py", line 158, in model
    default_type = int(default_type)
ValueError: invalid literal for int() with base 10: 'organisation'
```
(The string on the last line can also read `'site'` or `'person'` respectively)

Probable cause:
The `type` GET variable for the assignment type request gets populated as string in `modules/s3db/asset.py` on lines [1161](https://github.com/sahana/eden/blob/master/modules/s3db/asset.py#L1161), [1169](https://github.com/sahana/eden/blob/master/modules/s3db/asset.py#L1169) and [1177](https://github.com/sahana/eden/blob/master/modules/s3db/asset.py#L1177) however that variable seems to have different context that the one being evaluated by `modules/s3db/req.py` on line [158](https://github.com/sahana/eden/blob/master/modules/s3db/req.py#L158) where it's tried to be converted into integer.

**Comment by nursix** [comment]
That is correct - req interprets the type in the req context, and asset in the asset context. Both have type and status, so naturally that will collide.

IMHO neither model should make assumptions here, since both can be called cross-module. Ideally, req should look for reqtype/reqstatus and asset should look for assigntype/assignstatus or something like that. However, such a change would require quite a number of use-case migrations.

An alternative could be to check for the context (controller/function) to see if the type/status applies for asset or req - that would be a simpler fix, but it would also be less robust.

**Comment by nursix** [comment]
Actually, it's rather a bad thing to have model defaults or onaccept functions look for GET vars at all. They can be called from everywhere (including non-interactive, e.g. sync), and nothing that says that the current request context is addressed at them.

So maybe you can find a way to eliminate the GET vars here completely?

**Comment by trendspotter** [comment]
If that's supposed to be a prompt for brainstorming, then:

Option 1) Call URLs like `/eden/asset/asset/1/log/assignperson` instead of `/asset/asset/1/log/create?status=2&type=person` and have that `assignperson` method call `asset_log_prep()` with the extra parameters which are now in GET (status, type). Or have separate `prep()` and `onaccept()` until the end.

Option 2) Don't parametrize the form using variables at all and have a unified one, then decide in onaccept() based on the form data.

Option 3) Same as 2 and additionally have the fields shown/hidden using JS, which can get the data from fragment in the same manner as the GET does. (ie. `/asset/asset/1/log/create#status=2&type=person`

No idea if any of those qualify for an elegant solution.

Also note that it's probably not a good idea to have a [variable called `type`](https://github.com/sahana/eden/blob/master/modules/s3db/asset.py#L1041) as `type()` is a python builtin function.

**Comment by nursix** [comment]
It was a prompt for brainstorming ;)

I like option (1) best - and it doesn't even need any GET vars. Because:

When you call the asset/asset controller like ```/asset/asset/1/log/assignperson", then the ```asset_log_prep" can see that from ```r.method``` and thus decide the defaults for ```status``` and ```type``` itself (there is only one status/type combination for that method).

Then, after configuring the defaults for the fields, ```asset_log_prep``` can re-route the request to create by setting ```r.method``` (we've done that in other places, too).

And yes, naming variables like built-in functions is discouraged - we're routinely cleaning up those where they cross our paths, so probably a good thing for you to get into that habit too.

**Comment by trendspotter** [comment]
OK, I'm done with the first part in `asset_log_prep()`. As you've suggested I'm checking `r.method`, setting appropriate variables, then rerouting to `r.method = "create"`. Everything is nice and green and I see the proper forms.

Now, how can I get the values propagated also to `asset_log_onaccept()`? I don't see `r` in its context and  even though the form_vars provide distinct sets, I don't think building the logic around which fields get passed back is wise. Is there simple any way how can I get either `r` or smuggle some hidden fields into the form which won't affect the actual user input?

**Comment by nursix** [comment]
The standard way would be current.response.s3 - but I don't think that's necessary.

Both type and status are in the record - so they can be looked up from there.

**Comment by trendspotter** [comment]
Nope, the type is completely arbitrary and it's not stored anywhere. However `r = S3Request("asset", "asset", request)` seems to do the trick to get the proper `r.method` back, so I'll try with that one and you can give me some more pointers when I submit the PR.

**Comment by nursix** [comment]
Oh, you shouldn't try to re-instate the S3Request - that will trigger a lot of unnecessary processing.

Then better pass the method via current.response.s3.asset_log_method (i.e. set it in asset_log_prep, and inspect it in asset_log_onaccept).

**Comment by nursix** [comment]
Another option could be to decorate ```asset_log_onaccept``` and configure it in the ```asset_log_prep```, passing the method as parameter via the decorator. That would make more obvious /where/ you pass the parameter to.
