### ISSUE TITLE
Ability to specify relative date(time)s in URL queries

### ISSUE THREAD

**Issue by nursix** [sahana/eden#1447]
Current implementation requires ISO format absolute date(time) expressions in URL queries when filtering by date(time) fields.

That makes it impossible to store date/time filter expressions (e.g. in subscriptions, map layers) where they shall be relative to NOW (e.g. "14 days ago") - as those static expressions would not progress.

To overcome this, it should be made possible to specify relative date(time)s instead, like "-2Y" (2 years ago), or "-14D" (14 days ago), or "+24h" (24 hours from now).

A solution would implement an expression syntax (parser) for relative date(time)s, and apply it in the respective S3TypeConverter function when converting strings into date(time)s.

**Comment by timliu117** [comment]
Could you give me an example of where this would be useful within Sahana Eden? 
If I understand you correctly, when I enter +4D (from now, 03/01/2018), and this would return 03/05/2018?

**Comment by nursix** [comment]
There are several use-cases, the most obvious of which is stored filters (e.g. subscriptions, map layers). 

Take subscriptions - if people subscribe to "all CAP alerts of the last three days", then this filter would be stored as a string, and then parsed from that string at the time when the subscription is checked.

If you store the filter as "alert.date__gt=2018-02-27" (as it would be required now), then this is "last three days" today, but not tomorrow...or any future date.

If you could store this filter instead as "alert.date__gt=-3D", then this will always mean "last three days", not just today.

I am currently working on a solution for this, so happy to discuss it further if you have suggestions?

**Comment by nursix** [comment]
For a parser, I was imagining something like this:

```
import re
import datetime
from dateutil import relativedelta

def relative_datetime(dtexpr):

    dtexpr = dtexpr.strip()
    if dtexpr[0] not in ("+", "-"):
        return None

    syntax = re.compile(r"([+-]{0,1})([0-9]*)([YMDhms])")

    seconds = {"D": 86400,
               "h": 3600,
               "m": 60,
               "s": 1,
               }

    now = datetime.datetime.utcnow()

    then = now
    f = 1
    for m in syntax.finditer(dtexpr):

        try:
            value = int(m.group(2))
        except ValueError:
            continue

        sign = m.group(1)
        if sign == "-":
            f = -1
        elif sign == "+":
            f = 1

        unit = m.group(3)
        if unit == "Y":
            then += relativedelta.relativedelta(years = f * value)
        elif unit == "M":
            then += relativedelta.relativedelta(months = f * value)
        else:
            u = seconds.get(unit)
            if u:
                then += relativedelta.relativedelta(seconds = f * u * value)

    return then

print relative_datetime("-2D")      # two days ago
print relative_datetime("-1Y6M")    # 1 year and 6 months ago
print relative_datetime("+14D")     # 14 days from now
print relative_datetime("+36h")     # 36 hours from now
```

Maybe you can improve this, both for speed and flexibility?

The relative date/time string must be distinguishable from absolute date/time strings - which is why I would require it to start with + or -. After that, it can be any combination of relative interval expressions.

Note that these relative strings will always be generated, never entered by hand - so they don't need to look nice. But they must be URL-safe, should be as compact as possible and must not clash with any recognizable date/time format (in particular not with the ISO format).

I can add this parser in the right places, so if you want to make suggestions how to improve it...?

Speed matters, yes - but scalability less so (the relative strings won't be endlessly complex). Destructive testing also welcome (how can this parse be crashed?).

**Comment by nursix** [comment]
I implemented a first version here:
https://github.com/nursix/eden/commit/52682e18137e4f2a31a92e435add844fadcbdb9e

A first possible use-case could be this:
https://github.com/sahana/eden/blob/master/static/scripts/S3/s3.filter.js#L616
...as it can be simplified to construct a years-expression rather than computing dates.

You want to try this?

**Comment by timliu117** [comment]
I am sorry for the late reply, I have been thinking about a pass due situation that may break things down. Eg: You set the due day to be +3d(3 days from now), after 4 days,  what will the time slot show? +4d or 1 days past the due day?
