### ISSUE TITLE
CMS mangles links in HTML posts

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1452]
I have found the issue when I've tested the SAMBRO RSS and CAP feeds, but later found out that basically any CMS post with HTML link in it exhibits the problem. Whenever a HTML link is present in the post, CMS reparses it again in some weird way, creating a new link out of the `href` part while leaving the surrounding code unchanged. Eg from
```
<a href="http://blabla">blabla</a>
```
it creates
```
<a href="<a href=" http: blabla"">http://blabla"</a>"blabla
```

See the screenshot:

![sambro](https://user-images.githubusercontent.com/15286128/36050717-ed8e284a-0de7-11e8-8345-aef41b5633e4.PNG)

**Comment by nursix** [comment]
Yeah, that's a nice one!

This is the function responsible for the problem:
https://github.com/sahana/eden/blob/master/modules/s3/s3utils.py#L768
...it's not expecting markup in CMS posts but plain text, hence not detecting when a URL is inside of markup.

Now, this is a bit problematic here:

I find it utterly questionable whether we should render markup from external sources inside this datatable - I'd say clearly no as it is a security risk (can inject JS), and can give the most unexpected results. And it's not helpful here as this is the administration perspective, not the representation.

Secondly, if we by all means have to, then the representation function:
https://github.com/sahana/eden/blob/master/modules/s3db/cms.py#L226
...should detect whether the body already /is/ markup, and if yes, then not call URLise.

**Comment by nursix** [comment]
I'd refer this to @flavour as he's the CMS expert.

**Comment by trendspotter** [comment]
> I find it utterly questionable whether we should render markup from external sources inside this datatable - I'd say clearly no as it is a security risk...

Definitely agree on this one. CMS happily accept and save any `<script>` you give it, so this screams "Stored XSS" from miles away. If the markup should stay, it should at least be properly sanitized (html5lib may be a viable option).

**Comment by nursix** [comment]
That said, the whole point about CMS is to be able to render stored markup, /including/ scripts and even such that access the back-end with the authority of the current user.

Question is where the contents come from - whether they are created locally by a privileged user, or imported by an unsupervised background process. So, this may come down to vetting during import (feed parser), or post-import (review/approve), and is thus somewhat orthogonal to the current issue.

So, to resolve the rendering glitch, the represent-function should detect body markup and if found, not attempt to s3_URLise but render as-is.
