### ISSUE TITLE
Fullscreen map is shown in a narrow strip instead of fullscreen

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1459]
This is just a cosmetic (CSS) issue.

Clicking on the _View Fullscreen Map_ should show a map in fullscreen. Instead it does this:
![map](https://user-images.githubusercontent.com/15286128/36272514-063ff244-1282-11e8-87de-fa7ce9ffc900.jpg)

By experimenting with CSS, I've found out that all what it takes to fix it is to either remove `position: relative` from `body` in [foundation.css](https://github.com/sahana/eden/blob/18a9837839d595a58d197b9fef11015d517e3b8a/static/themes/default/foundation/foundation.css#L96) or add `position: inherit` to [`.x-window-maximized-ct`](https://github.com/sahana/eden/blob/58c2cb39229034871a72d4570b2fcaa58f6941a6/static/scripts/ext/resources/css/structure/window.css#L168) (which achieves pretty much the same), however I have no idea what other things may be broken by this fix.

**Comment by nursix** [comment]
Doesn't happen for me:
![mvc](https://user-images.githubusercontent.com/1257183/36276769-38aa81b0-128f-11e8-9c91-f1ca1e5beadd.png)

...neither in FF nor Chrome. Can you maybe specify the browser and version?

Neither of the CSS directives you mention gives a clear reason why it would look like in your screenshot - and consequently, the corrections you propose are not plausible.

**Comment by nursix** [comment]
However, I can see you have some menu modifications - do you have other modifications maybe that might interfere with the layout?

**Comment by nursix** [comment]
NB Full-screen map viewer shows NO menus - the fact that they are visible in your screen shot makes me suspicious. It doesn't look as if the browser has been switched into full-screen mode at all (see my screenshot - that's the point with "full screen map") - which could be a JavaScript problem rather than a CSS issue.

Any console messages, maybe?

**Comment by trendspotter** [comment]
Chrome 64, Windows 10, browser extensions disabled. And I got the same reported from Chrome on macOS 10.12.6. In Firefox 58, IE 11 and Edge 41 it works correctly.

This particular instance has some more modules activated, however there are no layout customization. More importantly, I just checked and I get the same results also on clean instance with default template. And I get the same also on different computer with the same browser. The screenshot is a full screenshot of my display, so the browser *is* in fullscreen mode. Strangely enough, when I visit `/eden/gis/map_viewing_client` and *then* press F11 to switch into fullscreen mode, it's rendered correctly.

The CSS "fix" was just me fumbling around in developers console, adjusting properties to see what got stuck and removing the body position helped to render it properly. No errors in console, just a buch of warnings about deprecated Google maps API.

**Comment by nursix** [comment]
Thanks - I think it's a Chrome glitch. Will work on a workaround.

**Comment by trendspotter** [comment]
Just for the sake of completeness - Clean default template in Chrome 64 on Xubuntu 17.10

![jbyj0rh](https://user-images.githubusercontent.com/15286128/36279750-5dc1b3a2-1298-11e8-8267-0887a8b58fa3.png)

**Comment by nursix** [comment]
Can you try this:
https://github.com/nursix/eden/commit/a30520b0b60b8acbc0c8d5e244bc6d4bfae6d912#diff-4ce00add828c9f0c2dd8763e7a69f802

(NB you must also download all the minified CSS unless running with debug=True)

**Comment by trendspotter** [comment]
Well. It works but
1) You haven't refreshed `static/themes/default/eden.min.css`
2) I have found another cosmetic issue related the floating legend on fullscreen, can I abuse this issue or should I open a new one? (I have to confirm it on a smaller display first)

**Comment by nursix** [comment]
default/eden.min.css coming.

For the other problem, please open a new issue.

**Comment by trendspotter** [comment]
I've just rebuilt the instances. Works out of the box. Thanks.
