### ISSUE TITLE
Supply Item creation ignores decimal separator settings

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1465]
Steps to reproduce:
Create an item in *Supply* module, fill in the mandatory fields and enter *Length* as `0,1`.

Expected behavior:
Value is accepted in accordance with `settings.L10n.decimal_separator`.

Actual behavior:
Validation of the value fails unless it is entered using dot as decimal separator.

I understand that this may be tricky to fix if such thing is not directly supported by Web2py.

**Comment by daveycrockett** [comment]
I would like to take a crack at this one, unless it is already in progress.

**Comment by nursix** [comment]
Go ahead.

This might be of help:
https://github.com/sahana/eden/blob/master/modules/s3/s3validators.py#L435

**Comment by nursix** [comment]
To clarify: whilst the issue report suggests that it may not be supported by web2py, it actually is - but obviously it doesn't look at the setting. 

We have a wrapper for the IS_FLOAT_IN_RANGE validator (namely, IS_FLOAT_AMOUNT) which generally allows to configure the separator per instance - but it doesn't fall back to the setting either.

So, the solution should be to have IS_FLOAT_AMOUNT fall back to the setting (still allowing per-instance override), and then apply it for the field(s) as needed. Ideally, this would be a little flexible and accept variations as long as they are unambiguous - but this isn't a hard requirement.

**Comment by daveycrockett** [comment]
Hey, sorry I didn't follow-up more quickly...thank you for the pointers! So far I've patched the method to properly load in the decimal and thousands separators from settings, and also added it to the `requires` for the fields specifications. I'm just debugging now, and then planned to go on the hunt for any other fields specifications that need the same fix, plus test cases. I should have more information (or more questions!) by tomorrow.

**Comment by nursix** [comment]
Maybe add a unit test (otherwise I will) for the fixed validator ;)

Looking forward to your PR :)

**Comment by daveycrockett** [comment]
Manual testing/debugging complete, and I'm working on a unit test now.

   ```grep -r "Field" * | grep "\"double\"" | wc -l``` shows 159 double fields declared in s3db. Does anyone that will be reviewing the PR have a preference as to whether this single PR should find all occurrences where the fix should be added, or just incrementally fix the case for supply item creation? Happy to do either! I'll send a partial PR once the unit test is added if that helps make the decision one way or another.

**Comment by nursix** [comment]
I'm not sure each and every double-field needs this - so I would prefer not to get a wholesale fix.

Also note:
- https://github.com/nursix/eden/commit/d29ffb3e82ef72b8f3e4a13c567aec7289f325c3 and 
- https://github.com/nursix/eden/commit/cae8791ec3ff85b29f56cf0762c22865e9c8c96e
before you continue.

**Comment by nursix** [comment]
Meaning: 

I've already added the unit test (feel free to add more samples it does not yet cover), and also fixed IS_FLOAT_AMOUNT to pass (along with IS_INT_AMOUNT, which had the same problem) - all in connection with a related issue (#1475).

I suppose your fix will improve this further? If so, please apply in supply first before you move on to other use-cases.

**Comment by nursix** [comment]
I reviewed+commented your commit here:
https://github.com/daveycrockett/eden/commit/2143781ac68ee72a3540fdc9e33bdb2545e3b6e7

The validator fix looks largely equivalent to the one I already applied, so I think you can leave that part out and focus on applying the validation rule in the respective use-cases.

Seems some of these may also need a minimum-value, besides format-sensitive validation.

**Comment by trendspotter** [comment]
Sorry for the late reply, but the original problem still remained untouched as it's still not possible to use comma (or whatever defined by `settings.L10n.decimal_separator`) as a decimal separator. Seems that some parts of https://github.com/daveycrockett/eden/commit/2143781ac68ee72a3540fdc9e33bdb2545e3b6e7 weren't carried over but should.

**Comment by nursix** [comment]
@trendspotter yes, the problem wasn't fixed by #1476 because https://github.com/sahana/eden/pull/1476/files applies IS_FLOAT_IN_RANGE instead of IS_FLOAT_AMOUNT even if the commit message said so.

If you exchange IS_FLOAT_IN_RANGE by IS_FLOAT_AMOUNT, things will work as expected. Don't forget to submit a PR with this fix.

**Comment by nursix** [comment]
Interestingly, the original attempt @daveycrockett in his own repo used correctly IS_FLOAT_AMOUNT.

Maybe he wants to correct it himself?

**Comment by daveycrockett** [comment]
Thanks for the offer...I'm pretty strapped for time at the moment, please
don't let me hold up a timely fix! If it isn't urgent, I'd be interested in
getting to it late next week.
