### ISSUE TITLE
Project/PartnerOrg/Region popup not closing after submission

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1473]
Split from #1472 as per the discussion there.

Steps to reproduce:
1. Set
    - `settings.org.regions = True`
    - `settings.org.regions_hierarchical = True`
    - `settings.project.mode_3w = True`
    - `settings.project.multiple_organisations = True`
2. Navigate to *Projects* and select *Partner Organization* -> *Create*.
3. Click on *Add Region* next to the *Region* field.
4. Fill in the region and click *Save*.

And apart from the popup not closing I'm getting also following trace in browser console:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery-1.11.3.js:358)
    at Object.<anonymous> (VM489 s3.popup.js:287)
    at Object.AjaxS3.onSuccess (S3.js:611)
    at Object.<anonymous> (S3.js:721)
    at fire (jquery-1.11.3.js:3148)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.js:3260)
    at done (jquery-1.11.3.js:9314)
    at XMLHttpRequest.callback (jquery-1.11.3.js:9718)
```

Also, strangely enough, the error does not occur when using the exact same popup in *Organizations* -> *Create Organization*.

**Comment by nursix** [comment]
The issue here is that when you create a region in the popup, and do *not* pick a zone (this is missing from your description above), then you violate a constraint of the "Region" field in the partner organisation form (only child regions are allowed, not parent-less "zones").

And if this is the first region you're ever creating, then that would result in zero new options for the "Region" field - a case that should not normally be possible when closing a *create*-popup. However, as we can see - it is possible after all.

As one can expect for unexpected edge cases, the "no new options" case is not caught in the popup script and crashes with the above error. Obviously, it shouldn't crash.

But it should not be possible to create regions without zone in the popup in the first place ;)

Fix coming up...
----

Note that "Regions" are a model related to a unique, highly specific use-case of the IFRC. They may thus not make any sense outside this particular context - or at least need a lot of additional work to make sense.

**Comment by nursix** [comment]
Like this:
https://github.com/nursix/eden/commit/cadd400e7a16cbf45a70792b070bfa55662bccea#diff-e0c01ed1772d9047f53e372930ec0d05R309
...ie. if no new options are returned, then do nothing, just cleanup+return

At the same time, denying creation of zone-less regions in the popup here:
https://github.com/nursix/eden/commit/cadd400e7a16cbf45a70792b070bfa55662bccea#diff-2b63fe823e51d593e8923cb7afccb634R87

If we wanted to be thorough (and @flavour may insist, let's see), then we should remove the options to create new regions in popups completely /if/ they are hierarchical.

**Comment by trendspotter** [comment]
Hmm... I can still reproduce the issue even after https://github.com/nursix/eden/commit/cadd400e7a16cbf45a70792b070bfa55662bccea ...and I get it even when I *do* select a zone. I'll try to dig up the rest of the config directives to complete the report, so we don't have to guess.

**Comment by trendspotter** [comment]
No, scratch that. I just got tangled between VM snapshosts and outdated docker cache. https://github.com/nursix/eden/commit/cadd400e7a16cbf45a70792b070bfa55662bccea works. Like you said, it doesn't allow me to create a region with no zone from the popup and it doesn't leave me hanging when I submit the form with all necessary data.

The only thing where I still dare to object is that when I create a new region using the popup, it doesn't fill the value to the select element in *Create Partner Organization* form and I need to refresh the page to see the new value.

**Comment by nursix** [comment]
I'm not entirely sure why that would be - maybe try to refresh your browser cache here (tricky, since the script is loaded in an iframe - best to wipe the cache entirely).

This part definitely works for me.

**Comment by nursix** [comment]
Checked again - working here.

**Comment by trendspotter** [comment]
Interesting. When I set just the config mentioned in the *steps to reproduce*, it works. But on the staging, where we have bunch of other settings, the `/eden/project/organisation/options.s3json?field=region_id` returns an empty object. Will investigate and update or create a new issue as needed.

**Comment by trendspotter** [comment]
`settings.project.multiple_organisations = True` causes it. And it's also the missing directive for the problems in the original report.
https://github.com/sahana/eden/blob/fc3765dbd835c95736c75a6b6d1a78aec599bdb5/controllers/project.py#L650-L664

**Comment by nursix** [comment]
Oh, I see - that would be the wrong controller for the options look-up. 

If you open the popup from project/partners, then it should also look up the options from project/partners and *not* from project/organisation, which is actually the controller of a completely different resource (namely, project_organisation).

Now, project_organisation is only ever relevant with multiple orgs, so the project/organisation controller diverts to org_organisation if multiple org is disabled - and that is why it sort-of "works" when you switch multiple orgs off. 

Obviously, such a hybrid controller is a rather ugly and terribly confusing and error-prone design (especially in this case) - and if it wouldn't break DRRPP, I think it should be thrown out. But as it is, we can't, so I've added this instead:
https://github.com/nursix/eden/commit/fb5c5f4fb6b6b9b6a84f53999698220a5d5b1dac
...to ensure the project/partners region_id look-up uses project/partners.
