### ISSUE TITLE
Chinese Translations Incorrect

### ISSUE THREAD

**Issue by lynnliu626** [sahana/eden#1488]
I went through the English to Chinese file in languages folder, and I found a lot of incorrect translations.  I am fluent in both languages and have fixed them on my virtual machine. I think it should be fixed.
For example, "yes" is translated to "点头", which means "nod" in Chinese.

**Comment by nursix** [comment]
The best option to get this fixed is for you to send a pull request with the corrected language file.

**Comment by nursix** [comment]
Fixed by https://github.com/sahana/eden/commit/bd359ebd4b4f46b37f1f66bce560ef54075881fe
