### ISSUE TITLE
New instalations instructions

### ISSUE THREAD

**Issue by crlsgms** [sahana/eden#1496]
Hello everyone.

On the installation instructions, it points up to debian7, is it still the only system homologated for the installation?

I followed up this guide: http://eden.sahanafoundation.org/wiki/InstallationGuidelines/Linux/Server/ApacheMySQL

please let me know if there is any other newer methods to install and deploy the tool, Im trying to setup an environment here so we could help people on the brumadinho disaster here in Minas Gerais - Brasil

thanks in advance

**Comment by flavour** [comment]
On Tue, 29 Jan 2019 at 12:31, Carlos Gomes <notifications@github.com> wrote:

> On the installation instructions, it points up to debian7, is it still the
> only system homologated for the installation?
>
> I followed up this guide:
> http://eden.sahanafoundation.org/wiki/InstallationGuidelines/Linux/Server/ApacheMySQL
>
> please let me know if there is any other newer methods to install and
> deploy the tool, Im trying to setup an environment here so we could help
> people on the brumadinho disaster here in Minas Gerais - Brasil
>

The best-supported way to install Sahana Eden is through the
WebSetup...this only supports Cherokee / PostgreSQL (on the last 3 Debian
Stables, latest preferred).
The instructions for this are on the Amazon EC2 page, although can be used
on other platforms:
http://eden.sahanafoundation.org/wiki/InstallationGuidelines/Amazon#a6:ConfigureInstanceDetails

If you prefer to use alternate web servers &/or databases, there are some
scripts here which are somewhat maintained:
https://github.com/sahana/eden_deploy_manual

So the Apache/MySQL works with Debian 8 or 7...they haven't yet been
tested/updated with Debian 9:
https://github.com/sahana/eden_deploy_manual/blob/master/install-eden-apache-mysql.sh#L6

Best Wishes,
Fran.

**Comment by crlsgms** [comment]
Oh thank you!

I just setup a fresh debian 9 install, and the scripts wont work, if there is anywhere to point that up would be nice.

I'll try with the ec2 installations instructions, thanks again, ill report here if I have any issues using it over debian 9

**Comment by flavour** [comment]
On Tue, 29 Jan 2019 at 13:12, Carlos Gomes <notifications@github.com> wrote:
> I just setup a fresh debian 9 install, and the scripts wont work, if there is anywhere to point that up would be nice.

The most obvious thing that will definitely fail if using unaltered
scripts on Debian 9 is that they will assume Debian 7 & hence Apache
2.2
I can update that part easily enough.
There may well, of course, be other issues to work through

F

**Comment by crlsgms** [comment]
That would be nice. 

Besides the filter to allow / deny changing to "require" in 2.4, I dont know what more issues with configuration that should be altered. 

If there is any way for me to help updating and testing the install script under debian 9, let me know

**Comment by crlsgms** [comment]
Other doubt I didnt found in the wiki / docs

After running the "install-eden-apache-mysql.sh" it asks for a template to use, where do I get the possible templates to use?

**Comment by flavour** [comment]
I have already updated that 1st part. Note that the mailing list is a better place for this discussion than an Issue. Yes, you can help test the script: run it stepwise & report back.

**Comment by flavour** [comment]
On Tue, 29 Jan 2019 at 14:18, Carlos Gomes <notifications@github.com> wrote:

> Other doubt I didnt found in the wiki / docs
>
> After running the "install-eden-apache-mysql.sh" it asks for a template to
> use, where do I get the possible templates to use?
>

The WebSetup is much better in this regard, which is one of the reasons we
recommend it

Meanwhile you can see the list here:
https://github.com/sahana/eden/tree/master/modules/templates

F

**Comment by crlsgms** [comment]
I tested the updated scripts, the installation worked with some erros on the end about permissions, but didnt prevent the application to run.

`chown: não foi possível acessar '/home/web2py/applications/admin/cache': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/admin/databases': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/admin/errors': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/admin/sessions': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/eden/cache': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/eden/errors': Arquivo ou diretório não encontrado
chown: não foi possível acessar '/home/web2py/applications/eden/uploads': Arquivo ou diretório não encontrado`
