### ISSUE TITLE
We would like to integrate

### ISSUE THREAD

**Issue by paulrsilva** [sahana/eden#1497]
Guys, we're working on Brumadinho disaster. We'd like to integrate any solution with your platform. If you are a Software Architect or are able to help us in the integration, please take a look in https://github.com/sosbrumadinho . Our Telegram group  is available at 
https://t.me/joinchat/DQBYpBdvDrhVA6EQwXZ9gg

**Comment by nursix** [comment]
Please use our mailing list for such communications:
https://groups.google.com/forum/?hl=en#!forum/sahana-eden

**Comment by flavour** [comment]
https://groups.google.com/forum/#!topic/sahana-eden/RSdftmrN1zk
