### ISSUE TITLE
PDF exports ignore font settings and break diacritics

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1498]
### Description:
Although there is a `settings.L10n.pdf_export_font` configuration directive, it is ignored in a lot of files and *Helvetica* font is hardcoded there instead. Most notably on multiple places in https://github.com/sahana/eden/blob/master/modules/s3/s3pdf.py, which causes PDF exports to render using wrong font without diacritics.

### Steps to reproduce:
1. Install *DejaVuSerif.ttf* and *DejaVuSerif-Bold.ttf* into `eden/static/fonts`.
2. Set `settings.L10n.pdf_export_font = ['DejaVuSerif', 'DejaVuSerif-Bold']` in `config.py`.
3. Start Sahana Eden.
4. Create an organization with following values:
   - Name: Příliš žluťoučký kůň úpěl ďábelské ódy
   - Website: https://something.long.enough.to.trigger.font.change.com
5. Export organization listing into PDF.

### Expected result:
[long-line-correct.pdf](https://github.com/sahana/eden/files/3076664/long-line-correct.pdf)

### Actual result:
[long-line-wrong.pdf](https://github.com/sahana/eden/files/3076665/long-line-wrong.pdf)

### Additional info:
If the line is short enough and doesn't wrap, the font change doesn't trigger and the line is rendered correctly - [short-line-correct.pdf](https://github.com/sahana/eden/files/3076666/short-line-correct.pdf). Unfortunately just one wrapped line is enough to switch font for the whole column.

As a workaround, we have supplied our own TTF files supporting diacritics into `eden/static/fonts`, renamed them to *Helvetica.ttf* and *Helvetica-Bold.ttf* and set `settings.L10n.pdf_export_font = ['Helvetica', 'Helvetica-Bold']`. This causes the PDF codec's [`set_fonts()`](https://github.com/sahana/eden/blob/48aaea7671c27af1052a68b199a74ceb400af3c2/modules/s3/codecs/pdf.py#L96-L103) to register our font as *Helvetica* and the exports are then rendered as expected.

The `settings.L10n.pdf_export_font` is used in IFRC template with *unifont* font. We have tried than one too and it exhibits the same behavior.
https://github.com/sahana/eden/blob/48aaea7671c27af1052a68b199a74ceb400af3c2/modules/templates/IFRC/config.py#L452-L461

**Comment by nursix** [comment]
Hi -- thanks for reporting this!

The actual PDF codec is here:
https://github.com/sahana/eden/blob/master/modules/s3/codecs/pdf.py

The problem you describe is a regression after a recent refactoring that would wrap overflowing cell contents in Paragraphs: whilst the font is correctly set for the table cell, it isn't set for those wrapper Paragraphs, hence falling back to default Helvetica.

Fix pushed: https://github.com/nursix/eden/commit/184d6270593486159171b6af85b0b7f4d17b2a52

**Comment by nursix** [comment]
P.S. https://github.com/sahana/eden/blob/master/modules/s3/s3pdf.py#L10
