### ISSUE TITLE
Requests to 'request' results in HTTP 500

### ISSUE THREAD

**Issue by pmitropoulos** [sahana/eden#1500]
Using Apache/MySQL installation, configuration scripts, a request to URL _/eden/req/index_ leads to 500, INTERNAL SERVER ERROR, see error log below.

```S'Traceback (most recent call last):\n  File "/home/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "applications/eden/compiled/controllers.req.req.py", line 1935, in <module>\n  File "/home/web2py/gluon/globals.py", line 421, in <lambda>\n    self._caller = lambda f: f()\n  File "applications/eden/compiled/controllers.req.req.py", line 105, in req\n  File "applications/eden/compiled/controllers.req.req.py", line 890, in req_controller\n  File "applications/eden/compiled/models.00_utils.py", line 244, in s3_rest_controller\n  File "applications/eden/modules/s3/s3rest.py", line 689, in __call__\n    output = postprocess(self, output)\n  File "applications/eden/compiled/controllers.req.req.py", line 747, in postp\nNameError: global name \'s3_str\' is not defined\n'```

**Comment by flavour** [comment]
Thankyou, fixed here:
https://github.com/sahana/eden/commit/f342c6664a20c6749f7ef058e0bf376d115fb359
