### ISSUE TITLE
Optimise by not loading auth_user_temp every request

### ISSUE THREAD

**Issue by flavour** [sahana/eden#1517]
Every request loads all tables used by AuthS3() in modules/s3/s3aaa.py
This currently includes the S3-custom table 'auth_user_temp' which is really not necessary as this only gets used as part of the user-registration use case.
Ideally this should be moved to it's own class in modules/s3db/auth.py so that it is only loaded when required.
This will mean the table has to be instantiated via s3db. instead of just db.

**Comment by hallamoore** [comment]
I'll take a pass at trying to implement this!

**Comment by hallamoore** [comment]
Whoops, I didn't use the right keyword in the commit message for the issue close automatically. @flavour can you close this issue?
