### ISSUE TITLE
Py 3: In-App notifications show as b'Logged in', etc

### ISSUE THREAD

**Issue by flavour** [sahana/eden#1523]
Py 3.7
Web2Py 2.18.3
Eden trunk
Windows 10

I tried changing the layout's {{=response.confirmation}} to {{=s3base.s3_str(response.confirmation)}} but no joy...I think there must be an earlier str() on the content so that this is actually s3_str("b'Logged in'")
I can't see where this is happening, though.

I thought perhaps here:
https://github.com/web2py/web2py/blob/master/gluon/globals.py#L433
Setup by:
https://github.com/web2py/yatl/blob/master/yatl/template.py#L652

However this wraps the s3_str() as well as the response.confirmation

**Comment by nursix** [comment]
I think the problem is rather the initialization of the message. I'll check it.

**Comment by nursix** [comment]
I think the problem is specific to web2py-2.18.3 - I cannot reproduce it in web2py-2.18.5. You may want to upgrade to 2.18.5 (needs a patch too, but I can provide it).

**Comment by flavour** [comment]
Yes, upgrading to Web2Py 2.18.5 fixes this, so that needs to be part of the new Py3 install scripts :)
Haven't encountered a need for a patch yet, but pls send over as I guess it'll bite sooner or later ;)
