### ISSUE TITLE
SAMBRO cap_info.csv import fails

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1530]
**Steps to reproduce:**
Perform a clean installation of SAMBRO template including the demo data.

**Expected result:**
Installation succeeds.

**Actual result:**
Installation fails while importing *cap_info.csv*
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/eden/models/zzz_1st_run.py", line 319, in <module>
    bi.perform_tasks(path)
  File "applications/eden/modules/s3/s3import.py", line 5032, in perform_tasks
    self.execute_import_task(task)
  File "applications/eden/modules/s3/s3import.py", line 4353, in execute_import_task
    extra_data=extra_data,
  File "applications/eden/modules/s3/s3resource.py", line 2492, in import_xml
    onconflict=onconflict)
  File "applications/eden/modules/s3/s3resource.py", line 2724, in import_tree
    log_items = self.get_config("oncommit_import_item"))
  File "applications/eden/modules/s3/s3import.py", line 3614, in commit
    success = item.commit(ignore_errors=ignore_errors)
  File "applications/eden/modules/s3/s3import.py", line 2544, in commit
    callback(onaccept, form, tablename=tablename)
  File "/srv/web2py/gluon/tools.py", line 81, in callback
    [action(form) for action in actions]
  File "applications/eden/modules/s3db/cap.py", line 1521, in info_onaccept
    update["event"] = itable.event_type_id.represent(info.event_type_id)
  File "applications/eden/modules/s3/s3fields.py", line 454, in __call__
    items = self._lookup([value], rows=rows)
  File "applications/eden/modules/s3/s3fields.py", line 772, in _lookup
    items[keys.get(k, k)] = theset[k] = represent_row(row)
  File "applications/eden/modules/s3/s3fields.py", line 377, in represent_row
    values = [row[f] for f in self.fields if row[f] not in (None, "")]
  File "/srv/web2py/gluon/packages/dal/pydal/objects.py", line 94, in __getitem__
    raise KeyError(key)
KeyError: 'name'
```

**Additional notes:**
We've initially though that it's because of the malformed data, but it happens also with the corrected CSVs from #1529 (actually any single record is enough to trigger it).

Also, we're still using python 2.7, planning to upgrade i the upcoming week. It doesn't seem like the problem is caused by it, but I'm mentioning it just in case.

**Comment by nursix** [comment]
Prepop for SAMBRO succeeds without errors for web2py-2.18.5 + latest Eden trunk. This is also a routine test for eden-stable, so it definitely did work there for the latest release.

There is no obvious cause for this within Eden, so can you please specify which web2py version you are using?

**Comment by Disassembler0** [comment]
Currently we have 2.18.3 (commit 6128d03) - the same as in
https://github.com/sahana/eden/blob/8d7bba62bfceace9bbe828110adc9b2217dd5d97/tests/travis/install_web2py.sh#L18-L19
Will try again with 2.18.5 in 30ish minutes and report back.

**Comment by nursix** [comment]
Okay, will investigate.

**Comment by nursix** [comment]
Still cannot reproduce it, sorry.

Could you perhaps produce debug-output during 1st run (settings.base.debug=True)?

**Comment by trendspotter** [comment]
So, after several hours of thinking I've lost my marbles I have an update.

The installation consistently fails with the above traceback on a clean system. However when I drop and recreate the database, clean Sahana's *database* directory, and rerun `./web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py` for the second time, it always works. This kept me profoundly perplexed. So I have checked what's the difference after the first failed run and apart from the obvious *\*.pyc* files, I have noticed that an extra file *models/0000_update_check.py* with content `CANARY_UPDATE_CHECK_ID = 4` is created.

So I have added the creation of this file with the same content into my installation steps just before database population, and lo and behold, the creation passes without any problems (except the GIS validation errors added today, but those don't terminate the script).

web2py-2.18.5 (commit 59700b8) behaves the same. Note that this is still on python 2.7.16 so maybe let's not delve into debugging and fixing just yet and I'll try to confirm if I still see the same on 3.x. Also the traceback has already been generated with `settings.base.debug=True`. There's nothing else useful (actually even the file name is printed only after a successful import, so I needed to crosscheck with *tasks.cfg*)

**Comment by nursix** [comment]
From what you describe, it seems that this is not a _clean_ install - rather mysterious that you should need to manually create the canary file, and that without it, there would be an error with the above traceback (there is no relationship between the two whatsoever).

What kind of system are you installing on? Could this be a permission problem (check default file permissions)?

**Comment by trendspotter** [comment]
Our main platform is LXC container Alpine 3.9, however as I have just figured out, I'm able to break it also elsewhere.

Dockerfile for your viewing pleasure:
(heavily abusing travis scripts and running as root for simplicity)
```Dockerfile
FROM ubuntu:18.04

# Define some variables
ENV DEBIAN_FRONTEND=noninteractive
ENV USER=root
ENV DB=postgres

# Make apt-get accept everything, update and install basic packages
RUN echo 'APT::Get::Assume-Yes "true";' >/etc/apt/apt.conf.d/yes \
 && apt-get update \
 && apt-get install git postgresql python-pip

# Install Sahana Eden
RUN git clone --depth 1 https://github.com/sahana/eden.git /srv/sahana/eden \
 && cd /srv/sahana/eden \
 && chmod +x tests/travis/* \
 && tests/travis/install_web2py.sh \
 && tests/travis/install_eden.sh

# Configure postgres
RUN echo 'local all all trust' >/etc/postgresql/10/main/pg_hba.conf \
 && echo 'host all all localhost trust' >>/etc/postgresql/10/main/pg_hba.conf \
 && service postgresql start \
 && psql -U postgres -c 'CREATE ROLE travis LOGIN' \
 && psql -U postgres -c 'CREATE DATABASE sahana OWNER travis' \
 && service postgresql stop

# Configure SAMBRO template, database and debugging
RUN cd /srv/web2py/ \
 && ./applications/eden/tests/travis/configure_db.sh \
 && sed -i 's|settings.base.template = "default"|settings.base.template = "SAMBRO"|' applications/eden/models/000_config.py \
 && sed -i 's|settings.base.debug = False|settings.base.debug = True|' applications/eden/models/000_config.py
```

Steps to reproduce:
```bash
# Build the container and run it as ephemeral
docker build -t ${LABEL} ${DIR_WITH_DOCKERFILE}
docker run -it --rm ${LABEL} /bin/bash

# Try to populate database and fail miserably
service postgresql start
cd /srv/web2py/
python web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py

# Exit the container and rerun a fresh instance
docker run -it --rm ${LABEL} /bin/bash

# Try to populate database with canary file present and succeed
service postgresql start
cd /srv/web2py/
echo 'CANARY_UPDATE_CHECK_ID = 4' >applications/eden/models/0000_update_check.py
mkdir applications/eden/databases
python web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py
```

**Comment by nursix** [comment]
Thanks, now I can reproduce it - and also identified the problem.

There are several possible ways to work around it, but only one that fixes the root cause - yet that one may be subject to debate before it gets into trunk, so I need you to have a little patience with it.

**Comment by nursix** [comment]
Note, however, that the setup procedure included in the travis config is really specific to that particular environment and for test-running the default template - but not suitable for production.

For a proper production setup, take sahana/eden_deploy_manual as a guideline.
