### ISSUE TITLE
Countries replaced during Warehouse import

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1544]
Steps to reproduce:

1. Go to *Warehouses* -> *Warehouses* -> *Import*
2. Import a simple CSV file containing name and country - [warehouses.txt](https://github.com/sahana/eden/files/4503428/warehouses.txt) (renamed to .txt because GitHub doesn't allow .csv attachments)
3. Observe that the import job details don't display the country.
4. Click on *Import*
5. Navigate back to *Warehouses* -> *Warehouses*
6. Observe that the countries differ from the import data (they are populated from a list of all countries in alphabetical order instead)

This happens also in different modules, e.g. Schools (*edu*), however doesn't happen in Organizations.

**Comment by flavour** [comment]
I think this is going to occur fairly widely.
It seems that whilst TUIDs only needed to be unique within a resource before, they are no longer, so resource prefixes are now critical, whereas before they were optional.
(I'm not sure what exactly caused this change)

**Comment by flavour** [comment]
I fixed the 2 you mention, if you find more then you should be able to easily fix using the same pattern :)

**Comment by nursix** [comment]
TUIDs need to be unique within the file (not the resource), and it has always 
been that way - nothing has changed in this regard.

måndag 20 april 2020 kl. 15:31:23 CEST skrev  Fran Boon:

**Comment by flavour** [comment]
I really believe it didn't have to be....these import files used to work fine.
The other change is that records are now always imported in order, whereas before they were randomised.
