### ISSUE TITLE
Newly added supplier doesn't appear on suppliers list

### ISSUE THREAD

**Issue by tomaszsmyczynski** [sahana/eden#1547]
System Tested:
https://covid19sahana.um.warszawa.pl

Version:
1.0.3-stable (2020-03-19 09:03:18)

Browser:
Chrome 81
Windows 10

Prerequisites:
User should be logged in to the system.

URL(s) where bug was encountered:
* https://covid19sahana.um.warszawa.pl/eden/inv/supplier

Steps:
1) Click ‘Create Supplier’ and fill required form fields with "type" set to "Supplier".
2) Click ‘Save’.
3) Refresh page.

Expected Result:

    Newly added supplier should appear in suppliers entry list.

Actual Result:

    New supplier entry doesn't appear on the list, to see it there is need to go to organization module entry list.

**Comment by flavour** [comment]
This works fine when I test locally with the default template.
You shouldn't need to set the Type on the inv/supplier page as this is defaulted/hidden.
So you have 2 differences in your template?
I could guess that you don't have Supplier as an Organisation Type, but I have no login to your system to see.

**Comment by tomaszsmyczynski** [comment]
It turned out that the organization type was manually translated by one of the users instead of being exported to a translation file and the filters stopped working because of that.
