### ISSUE TITLE
IndexError in Vulnerability module during database population

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1562]
**Steps to reproduce:**

1) Create or use a template with "vulnerability" module enabled (currently used by _IFRC_ and commented in _default_ and _RMSAmericas_)
2) Attempt to update/populate database via `web2py.py -S eden -M -R applications/eden/static/scripts/tools/noop.py` using the current Sahana Eden master (91eb815386e0bdc0c4a992f8de223acdcb84b973)

**Expected result:**

Database population succeeds.

**Actual result:**
```
Traceback (most recent call last):
  File "/srv/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "applications/eden/models/zzz_1st_run.py", line 389, in <module>
    s3db.vulnerability_rebuild_all_aggregates()
  File "/srv/web2py/applications/eden/modules/s3db/vulnerability.py", line 685, in vulnerability_rebuild_all_aggregates
    current.s3task.run_async("vulnerability_update_aggregates",
  File "/srv/web2py/applications/eden/modules/s3/s3task.py", line 278, in run_async
    tasks[task](*args, **vars)
  File "applications/eden/models/tasks.py", line 615, in vulnerability_update_aggregates
    result = s3db.vulnerability_update_aggregates(records)
  File "/srv/web2py/applications/eden/modules/s3db/vulnerability.py", line 757, in vulnerability_update_aggregates
    if isinstance(records[0]["date"], (datetime.date, datetime.datetime)):
IndexError: list index out of range
```

The `records` variable listed in the last line of traceback is populated with string value `'[]'`. Possibly some incompatibility with the recently updated web2py version?

**Comment by Halain00** [comment]
investigations in progress

**Comment by nursix** [comment]
The ```records``` parameter can be either Python-encoded (i.e. a list), or JSON-encoded (i.e. a string) - depending on how the aggregates update is invoked. 

During prepop, it would be called with run_async, which uses the JSON-encoding. If you didn't prepopulate any vulnerability data (which probably you didn't), then the records parameter would be ```'[]'```, as you've seen it.

But while an empty Python-list would have been caught, an empty JSON-list would be missed as the JSON-decoding was run only after the empty-check. So, I moved the JSON-decoding before the empty-check, fixing the problem.
