### ISSUE TITLE
[SAFIRE] Action Plan, Add Person failed

### ISSUE THREAD

**Issue by waidyanatha** [sahana/eden#1578]
I created a new positioned = "Mountain Search and Rescue"
Tried to create a new person then [got this error](https://bhutan.aidiq.com/eden/admin/ticket/eden/194.5.48.247.2021-09-20.02-12-38.78a632ff-b799-4139-9b6b-187fc526769b)

<h1>Error ticket for "eden"</h1>
<h2>Ticket 194.5.48.247.2021-09-20.02-12-38.78a632ff-b799-4139-9b6b-187fc526769b</h2><br><br>
<h3>Error traceback</h3>

1.Traceback (most recent call last):  
2. File "/home/prod/gluon/restricted.py", line 219, in restricted    exec(ccode, environment)  
3. File "applications/eden/compiled/controllers.pr.person.py", line 714, in <module>  
4. File "/home/prod/gluon/globals.py", line 430, in <lambda>    self._caller = lambda f: f()  
5. File "applications/eden/compiled/controllers.pr.person.py", line 219, in person  File "applications/eden/compiled/models.00_utils.py", line 255, in s3_rest_controller  
6. File "/home/prod/applications/eden/modules/s3/s3rest.py", line 628, in __call__    pre = preprocess(self)  
7. File "applications/eden/compiled/controllers.pr.person.py", line 128, in prep
8. AttributeError: 'Table' object has no attribute 'missing'

**Comment by flavour** [comment]
Resolved, thanks!
