### ISSUE TITLE
[SAFIRE] action plan data getting duplicated in incidents

### ISSUE THREAD

**Issue by waidyanatha** [sahana/eden#1579]
The Organizations and Event Action Plan (CMS) are getting copied or duplicated in the other Incidents; e.g. Infectious Bursal Disease escalation in Samtse. Persistent through out all other incidents. The Event Action Plan is not common and will vary by Incident type.  

To recreate

1. Start two separate call logs
2. assign the incident to the first and the action plan
3. assign incident to the second and check the action plan, you should see the data from first incident replicated

**Comment by flavour** [comment]
I am unable to see a problem when trying to reproduce this:
1. OK...there are already 2 call logs in prepop for Animal Die Off...they have the same description, which is an error as 1 is in Chhukha not Samtse, but that's not pertinent to this point
2. There are no Incidents to Assign to yet, so we create a New Incident from the Incident Report, ok...then we apply the Scenario template to it's Action Plan, ok
3. Do we 'Assign Incident' to the 2nd report? If so then there is only a single Incident...which, yes, has it's Action Plan still visible from the earlier Scenario application...or do we also create a 'New Incident'? If I test the latter then it is a separate Incident with a blank Action Plan.

**Comment by flavour** [comment]
Looking at the Demo server, I see what your issue is...it's not the whole Action Plan which is duplicated....just the Organisations section of it. This will be a filtering issue...no actual duplication, just that we see all in all...anyway, now I get the issue I can resolve :)

**Comment by flavour** [comment]
Resolved, thanks! :)
