### ISSUE TITLE
default template has doubled sentence in comment

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1585]
in this file https://github.com/sahana/eden/blob/master/modules/templates/default/project_theme.csv

there are two rows: 

**Economics of DRR** and  **Food Security & Agriculture** with same comment: **cost benefit analysis, disaster risk financing, financial effects of disasters, poverty and disaster risk, risk sharing, socio-economic impacts of disasters**

in addition doubled at the second row. Probably wrong

**Comment by flavour** [comment]
Thanks!
