### ISSUE TITLE
Module specific maps show blank page with text "None"

### ISSUE THREAD

**Issue by trendspotter** [sahana/eden#1588]
Navigating to any map page outside of gis module displays blank page only with text "None". Presumably some return value conversion goes wrong. No ticket is generated or traceback emitted to web server log. This is visible even on the official Demo site, see e.g.

- https://demo.eden.sahanafoundation.org/eden/org/office/map
- https://demo.eden.sahanafoundation.org/eden/project/location/map
- https://demo.eden.sahanafoundation.org/eden/vehicle/vehicle/map

**Comment by flavour** [comment]
Thanks!
